-- Cooker items configuration
-- This file contains item lists used by the generic cooker core
local lf = maidroid.lf
local all_cookable_items = {
    { item_name = "farming:flour_multigrain", count = 5 },
    { item_name = "farming:bread_slice",      count = 5 },
    { item_name = "group:food_corn",          count = 5 },
    { item_name = "group:food_sugar",         count = 5 },
    { item_name = "bucket:bucket_water",      count = 5 },
    { item_name = "farming:pumpkin_dough",    count = 5 },
    { item_name = "farming:rice_flour",       count = 5 },
    { item_name = "farming:tofu",             count = 5 },
    { item_name = "farming:flour",            count = 5 },
    { item_name = "farming:cocoa_beans_raw",  count = 5 },
    { item_name = "default:papyrus",          count = 5 },
    { item_name = "group:food_potato",        count = 5 },
    { item_name = "farming:seed_sunflower",   count = 5 },
}

local all_farming_outputs = {
    "farming:flour", "farming:flour_multigrain", "farming:bread_slice 5", "farming:toast_sandwich", "farming:garlic_clove 8", "farming:garlic", "farming:garlic 9", "farming:popcorn", "farming:cornstarch",
    "farming:bottle_ethanol", "farming:coffee_cup", "farming:chocolate_dark", "farming:chocolate_block", "farming:chocolate_dark 9", "farming:chili_powder", "farming:chili_bowl", "farming:carrot_juice", "farming:blueberry_pie", "farming:muffin_blueberry 2", "farming:tomato_soup",
    "farming:glass_water 4", "farming:sugar_cube", "farming:salt 9", "farming:salt_crystal", "farming:mayonnaise", "farming:rose_water", "farming:turkish_delight 4", "farming:garlic_bread", "farming:donut 3", "farming:donut_chocolate",
    "farming:donut_apple", "farming:porridge", "farming:jaffa_cake 3", "farming:apple_pie", "farming:cactus_juice", "farming:pasta", "farming:mac_and_cheese", "farming:spaghetti", "farming:bibimbap", "farming:burger", "farming:salad", "farming:smoothie_berry",
    "farming:spanish_potatoes", "farming:potato_omelet", "farming:paella", "farming:flan", "farming:cheese_vegan", "farming:butter_vegan", "farming:onigiri", "farming:gyoza 4", "farming:mochi", "farming:gingerbread_man 3", "farming:mint_tea", "farming:onion_soup",
    "farming:pea_soup", "farming:pepper_ground", "farming:pineapple_ring 5", "farming:pineapple_juice", "farming:pineapple_juice 2", "farming:potato_salad", "farming:melon_8", "farming:melon_slice 4", "farming:pumpkin", "farming:pumpkin_slice 4", "farming:pumpkin_dough",
    "farming:smoothie_raspberry", "farming:rhubarb_pie", "farming:rice_flour", "farming:soy_sauce", "farming:soy_milk", "farming:tofu", "farming:vanilla_extract", "farming:jerusalem_artichokes",
    "farming:cookie 8", "farming:carrot_gold", "farming:beetroot_soup", "farming:sunflower_oil", "farming:sunflower_bread", "farming:bowl 4"
}

local all_tools = {
    "default:axe_bronze",
    "default:axe_steel",
    "default:pick_bronze",
    "default:pick_steel",
    "default:sword_bronze",
    "default:sword_steel",
    "lottores:copperaxe",
    "lottores:copperpick",
    "lottores:coppersword",
    "lottores:galvornaxe",
    "lottores:galvornpick",
    "lottores:galvornsword",
    "lottores:goldaxe",
    "lottores:goldpick",
    "lottores:goldsword",
    "lottores:mithrilaxe",
    "lottores:mithrilpick",
    "lottores:mithrilsword",
    "lottores:silveraxe",
    "lottores:silverpick",
    "lottores:silversword",
    "lottores:tinaxe",
    "lottores:tinpick",
    "lottores:tinsword",
    "lottweapons:bronze_battleaxe",
    "lottweapons:bronze_spear",
    "lottweapons:bronze_warhammer",
    "lottweapons:copper_battleaxe",
    "lottweapons:copper_spear",
    "lottweapons:copper_warhammer",
    "lottweapons:elven_sword",
    "lottweapons:galvorn_battleaxe",
    "lottweapons:galvorn_spear",
    "lottweapons:galvorn_warhammer",
    "lottweapons:gold_battleaxe",
    "lottweapons:gold_spear",
    "lottweapons:gold_warhammer",
    "lottweapons:mithril_battleaxe",
    "lottweapons:mithril_spear",
    "lottweapons:mithril_warhammer",
    "lottweapons:orc_sword",
    "lottweapons:silver_battleaxe",
    "lottweapons:silver_spear",
    "lottweapons:silver_warhammer",
    "lottweapons:steel_battleaxe",
    "lottweapons:steel_spear",
    "lottweapons:steel_warhammer",
    "lottweapons:stone_battleaxe",
    "lottweapons:stone_spear",
    "lottweapons:stone_warhammer",
    "lottweapons:tin_battleaxe",
    "lottweapons:tin_spear",
    "lottweapons:tin_warhammer",
    "lottarmor:boots_bronze",
    "lottarmor:boots_copper",
    "lottarmor:boots_galvorn",
    "lottarmor:boots_gold",
    "lottarmor:boots_mithril",
    "lottarmor:boots_silver",
    "lottarmor:boots_steel",
    "lottarmor:boots_tin",
    "lottarmor:chestplate_bronze",
    "lottarmor:chestplate_copper",
    "lottarmor:chestplate_galvorn",
    "lottarmor:chestplate_gold",
    "lottarmor:chestplate_mithril",
    "lottarmor:chestplate_silver",
    "lottarmor:chestplate_steel",
    "lottarmor:chestplate_tin",
    "lottarmor:helmet_bronze",
    "lottarmor:helmet_copper",
    "lottarmor:helmet_galvorn",
    "lottarmor:helmet_gold",
    "lottarmor:helmet_mithril",
    "lottarmor:helmet_silver",
    "lottarmor:helmet_steel",
    "lottarmor:helmet_tin",
    "lottarmor:leggings_bronze",
    "lottarmor:leggings_copper",
    "lottarmor:leggings_galvorn",
    "lottarmor:leggings_gold",
    "lottarmor:leggings_mithril",
    "lottarmor:leggings_silver",
    "lottarmor:leggings_steel",
    "lottarmor:leggings_tin",
    "lottarmor:shield_bronze",
    "lottarmor:shield_copper",
    "lottarmor:shield_galvorn",
    "lottarmor:shield_gold",
    "lottarmor:shield_mithril",
    "lottarmor:shield_silver",
    "lottarmor:shield_steel",
    "lottarmor:shield_tin"
}

-- Function to detect if an item name follows cookable tool naming patterns
local function is_cookable_tool(tool_name)
    if not tool_name or type(tool_name) ~= "string" then
        return false
    end
    
    -- Exact lookup - check if the tool is in our all_tools list
    for _, tool in ipairs(all_tools) do
        if tool == tool_name then
            return true
        end
    end
    
    return false
end

local all_furnace_inputs = {
    "basic_materials:oil_extract",
    "basic_materials:paraffin",
    "basic_materials:terracotta_base",
    "basic_materials:wet_cement",
    "bones:bone",
    "bucket:bucket_water",
    "building_blocks:tar_base",
    "christmas_decor:gingerbread_man_raw",
    "darkage:basalt_cobble",
    "darkage:gneiss_cobble",
    "darkage:mud",
    "darkage:old_tuff_bricks",
    "darkage:ors_cobble",
    "darkage:rhyolitic_tuff_rubble",
    "darkage:schist",
    "darkage:shale",
    "darkage:slate",
    "darkage:slate_cobble",
    "darkage:tuff_rubble",
    "darkage:wood_frame",
    "default:axe_bronze",
    "default:axe_steel",
    "default:clay_lump",
    "default:cobble",
    "default:copper_lump",
    "default:desert_cobble",
    "default:desert_sand",
    "default:desert_stone",
    "default:glass",
    "default:gold_ingot",
    "default:gold_lump",
    "default:gravel",
    "default:iron_lump",
    "default:leaves",
    "default:obsidian_shard",
    "default:papyrus",
    "default:pick_bronze",
    "default:pick_steel",
    "default:sand",
    "default:silver_sand",
    "default:sword_bronze",
    "default:sword_steel",
    "farming:bread_slice",
    "farming:cocoa_beans_raw",
    "farming:corn",
    "farming:flour",
    "farming:flour_multigrain",
    "farming:potato",
    "farming:pumpkin_dough",
    "farming:rice_flour",
    "farming:seed_rice",
    "farming:seed_sunflower",
    "farming:sugar",
    "farming:tofu",
    "homedecor:plastic_base",
    "homedecor:skylight_frosted",
    "lottarmor:boots_bronze",
    "lottarmor:boots_copper",
    "lottarmor:boots_galvorn",
    "lottarmor:boots_gold",
    "lottarmor:boots_mithril",
    "lottarmor:boots_silver",
    "lottarmor:boots_steel",
    "lottarmor:boots_tin",
    "lottarmor:chestplate_bronze",
    "lottarmor:chestplate_copper",
    "lottarmor:chestplate_galvorn",
    "lottarmor:chestplate_gold",
    "lottarmor:chestplate_mithril",
    "lottarmor:chestplate_silver",
    "lottarmor:chestplate_steel",
    "lottarmor:chestplate_tin",
    "lottarmor:helmet_bronze",
    "lottarmor:helmet_copper",
    "lottarmor:helmet_galvorn",
    "lottarmor:helmet_gold",
    "lottarmor:helmet_mithril",
    "lottarmor:helmet_silver",
    "lottarmor:helmet_steel",
    "lottarmor:helmet_tin",
    "lottarmor:leggings_bronze",
    "lottarmor:leggings_copper",
    "lottarmor:leggings_galvorn",
    "lottarmor:leggings_gold",
    "lottarmor:leggings_mithril",
    "lottarmor:leggings_silver",
    "lottarmor:leggings_steel",
    "lottarmor:leggings_tin",
    "lottarmor:shield_bronze",
    "lottarmor:shield_copper",
    "lottarmor:shield_galvorn",
    "lottarmor:shield_gold",
    "lottarmor:shield_mithril",
    "lottarmor:shield_silver",
    "lottarmor:shield_steel",
    "lottarmor:shield_tin",
    "lottfarming:barley",
    "lottfarming:pipeweed",
    "lottfarming:potato",
    "lottfarming:tomatoes",
    "lottfarming:turnips",
    "lottmobs:meat_raw",
    "lottmobs:pork_raw",
    "lottores:copperaxe",
    "lottores:copperpick",
    "lottores:coppersword",
    "lottores:galvornaxe",
    "lottores:galvornpick",
    "lottores:galvornsword",
    "lottores:goldaxe",
    "lottores:goldpick",
    "lottores:goldsword",
    "lottores:lead_lump",
    "lottores:limestone",
    "lottores:mithril_lump",
    "lottores:mithrilaxe",
    "lottores:mithrilpick",
    "lottores:mithrilsword",
    "lottores:orc_lump",
    "lottores:rough_rock_lump",
    "lottores:silver_ingot",
    "lottores:silver_lump",
    "lottores:silveraxe",
    "lottores:silverpick",
    "lottores:silversword",
    "lottores:tin_lump",
    "lottores:tinaxe",
    "lottores:tinpick",
    "lottores:tinsword",
    "lottother:stony_blue_gem",
    "lottother:stony_purple_gem",
    "lottother:stony_red_gem",
    "lottother:stony_white_gem",
    "lottweapons:bronze_battleaxe",
    "lottweapons:bronze_spear",
    "lottweapons:bronze_warhammer",
    "lottweapons:copper_battleaxe",
    "lottweapons:copper_spear",
    "lottweapons:copper_warhammer",
    "lottweapons:elven_sword",
    "lottweapons:galvorn_battleaxe",
    "lottweapons:galvorn_spear",
    "lottweapons:galvorn_warhammer",
    "lottweapons:gold_battleaxe",
    "lottweapons:gold_spear",
    "lottweapons:gold_warhammer",
    "lottweapons:mithril_battleaxe",
    "lottweapons:mithril_spear",
    "lottweapons:mithril_warhammer",
    "lottweapons:orc_sword",
    "lottweapons:silver_battleaxe",
    "lottweapons:silver_spear",
    "lottweapons:silver_warhammer",
    "lottweapons:steel_battleaxe",
    "lottweapons:steel_spear",
    "lottweapons:steel_warhammer",
    "lottweapons:stone_battleaxe",
    "lottweapons:stone_spear",
    "lottweapons:stone_warhammer",
    "lottweapons:tin_battleaxe",
    "lottweapons:tin_spear",
    "lottweapons:tin_warhammer",
    "vessels:glass_fragments",
    "vessels:steel_bottle"    
}


all_take_item_groups = {
"group:food_apple",
"group:food_artichoke",
"group:food_banana",
"group:food_barley",
"group:food_beans",
"group:food_beetroot",
"group:food_blackberries",
"group:food_blueberries",
"group:food_bowl",
"group:food_bread",
"group:food_butter",
"group:food_cabbage",
"group:food_carrot",
"group:food_cheese",
"group:food_chicken_raw",
"group:food_chicken",
"group:food_chili_pepper",
"group:food_cocoa",
"group:food_coffee",
"group:food_corn_cooked",
"group:food_corn",
"group:food_cucumber",
"group:food_egg",
"group:food_flour",
"group:food_garlic_clove",
"group:food_gelatin",
"group:food_glass_water",
"group:food_lemon",
"group:food_lettuce",
"group:food_meat_raw",
"group:food_meat",
"group:food_milk_glass",
"group:food_milk",
"group:food_mint",
"group:food_mushroom",
"group:food_oats",
"group:food_oil",
"group:food_olive_oil",
"group:food_onion",
"group:food_orange",
"group:food_parsley",
"group:food_pasta",
"group:food_peas",
"group:food_peppercorn",
"group:food_pineapple_ring",
"group:food_pineapple",
"group:food_potato",
"group:food_pumpkin_slice",
"group:food_raspberries",
"group:food_rice",
"group:food_rose_water",
"group:food_rye",
"group:food_salt",
"group:food_skillet",
"group:food_soy",
"group:food_strawberry",
"group:food_sugar",
"group:food_sunflower_seeds_toasted",
"group:food_sunflower_seeds",
"group:food_toast",
"group:food_tomato",
"group:food_vanilla",
"group:food_wheat",
"group:wood",

}

all_take_item_farming = {
"bucket:bucket_river_water",
"bucket:bucket_water",
"default:cactus",
"default:gold_lump",
"default:snow",
"dye:orange",
"dye:pink",
"dye:yellow",
"farming:baked_potato",
"farming:baking_tray",
"farming:barley",
"farming:bottle_ethanol",
"farming:bread_slice",
"farming:bread",
"farming:caramel",
"farming:chili_pepper",
"farming:chocolate_block",
"farming:chocolate_dark",
"farming:cutting_board",
"farming:donut",
"farming:garlic_braid",
"farming:garlic_clove",
"farming:garlic",
"farming:hemp_fibre",
"farming:juicer",
"farming:melon_8",
"farming:melon_slice",
"farming:mixing_bowl",
"farming:mortar_pestle",
"farming:oat",
"farming:pepper_red",
"farming:pot",
"farming:pumpkin_8",
"farming:pumpkin_slice",
"farming:rice",
"farming:rye",
"farming:salt_crystal",
"farming:salt",
"farming:saucepan",
"farming:skillet",
"farming:soy_milk",
"farming:sugar",
"farming:sunflower_oil",
"farming:toast",
"farming:vanilla_extract",
"farming:wheat",
"flowers:rose",
"vessels:drinking_glass",
"vessels:glass_bottle",
"default:coal_lump"
}

all_take_item_names=all_take_item_farming

return {
    all_cookable_items = all_cookable_items,
    all_farming_outputs = all_farming_outputs,
    all_furnace_inputs = all_furnace_inputs,
    all_tools = all_tools,
    all_take_item_names = all_take_item_names,
    is_cookable_tool = is_cookable_tool
}


